<?php
use darkowl\user_manager\code\cDBConfig;

use \darkowl\user_manager\code;
require_once 'cDBConfig.php';
$obj_DBConfig = new cDBConfig();
// This file generated by Propel 1.6.4 convert-conf target
// from XML runtime conf file /home/darkowl/git/do-php-user-manager/User_Manager/src/main/config/propel/runtime-conf.xml
$conf = array (
		'datasources' =>
		array (
				'user_manager' =>
				array (
						'adapter' => $obj_DBConfig->getType(),
						'connection' =>
						array (
								'dsn' => $obj_DBConfig->getDNS(),
								'user' => $obj_DBConfig->getUserName(),
								'password' => $obj_DBConfig->getPassword(),
						),
				),
				'default' => 'user_manager',
		),
		'generator_version' => '1.6.4',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-user_manager-conf.php');
return $conf;