<?php
namespace MidnightPublishing\User_Manager;

use MidnightPublishing\User_Manager\conf\cDBConfig;

/**
 * Include the MidnightPublishing Autoloader
 */
require_once 'MP_Autoloader.php';

class cPropelConnector
{
	public static function initPropel()
	{
		if(!defined("PROPEL_INIT"))
		{
			define("PROPEL_INIT",TRUE);
			require_once 'propel/Propel.php';
				
			// Initialize Propel with the runtime configuration
			Propel::init(self::getConfig());

			// Add the generated 'classes' directory to the include path
			set_include_path("classes" . PATH_SEPARATOR . get_include_path());
		}
	}

	public static function getConfig()
	{
		$obj_DBConfig = new cDBConfig();
		$conf = array (
				'datasources' =>
				array (
						'user_manager' =>
						array (
								'adapter' => $obj_DBConfig->getType(),
								'connection' =>
								array (
										'dsn' => $obj_DBConfig->getDNS(),
										'user' => $obj_DBConfig->getUserName(),
										'password' => $obj_DBConfig->getPassword(),
								),
						),'mysql' =>
						array (
								'adapter' => $obj_DBConfig->getType(),
								'connection' =>
								array (
										'dsn' => $obj_DBConfig->getType().":"."host=".$obj_DBConfig->getHost().";dbname=mysql;",
										'user' => $obj_DBConfig->getUserName(),
										'password' => $obj_DBConfig->getPassword(),
								),
						),
						'default' => 'user_manager',
				),
				'generator_version' => '1.6.6',
		);
		$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-user_manager-conf.php');
		return $conf;
	}


	// This file generated by Propel 1.6.6 convert-conf target
	// from XML runtime conf file /home/darkowl/git/do-php-user-manager/User_Manager/src/main/config/propel/runtime-conf.xml

}