<?php
// This file generated by Propel 1.6.8 convert-conf target
// from XML runtime conf file /home/Randy.Blancett/workspace/do-php-user-manager/User_Manager/conf/propel/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'user_manager' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=user_manager',
        'user' => 'propel',
        'password' => 'propel',
      ),
    ),
    'default' => 'user_manager',
  ),
  'generator_version' => '1.6.8',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-user_manager-conf.php');
return $conf;